### PR TITLE
#678@patch: Assign of window.location.href.

### LINKED ISSUE #678: regression: assign of window.location.href
**Describe the bug**

Starting with version 7.8.0, setting the `href` property like this:
```
window.location.href = '/foo'
```

Will throw an exception: `ERR_INVALID_URL`.

**To Reproduce**
1. Create a test with happy-dom
2. In the test, insert `window.location.href = '/foo'`
3. See error `ERR_INVALID_URL`

**Expected behavior**
I can set the `href` property using a string which doest not represent a full url, in the same exact way in which both chrome and firefox works.

**Screenshots**
image

**Device:**
 - OS: OS X
 - Browser: Vitest
 - Version: v0.25.6

**Additional context**
This happens using happy-dom during tests.

### PR DESCRIPTION
**Pull request by Mas0nShi**
Fixes #678.

### CODE REVIEW

File: packages/happy-dom/src/location/Location.ts [hunk 1]
```diff
@@ -11,6 +11,13 @@ export default class Location extends URL {
 		super('about:blank');
 	}
 
+	/**
+	 * Override set href.
+	 */
+	set href(value: string) {
+		super.href = new URL(value, this).href;
```
Comment (ilteoood) [inline packages/happy-dom/src/location/Location.ts:18]: I don't think that this fixes the issue. If you set /Foo as value, the new url will throw an error

File: packages/happy-dom/test/location/Location.test.ts [hunk 2]
```diff
@@ -30,4 +30,12 @@ describe('Location', () => {
 			expect(location.href).toBe(HREF);
 		});
 	});
+
+	describe('href', () => {
+		it('Set href.', () => {
+			location.replace(HREF);
```
Comment (ilteoood) [inline packages/happy-dom/test/location/Location.test.ts:36]: You should test against a plain string like /Foo instead of using a valid url

Comment (Mas0nShi) [reply packages/happy-dom/test/location/Location.test.ts:36]: did you means `location.href = '/foo'` directly, like this:

```javascript
const {Window} = require('happy-dom');
const window = new Window();

window.location.href = '/foo'
```

Comment (ilteoood) [reply packages/happy-dom/test/location/Location.test.ts:36]: Yes, exactly. I'm watching this from my phone but it seems that HREF is a complete and valid url.

Comment (Mas0nShi) [reply packages/happy-dom/test/location/Location.test.ts:36]: > Yes, exactly. I'm watching this from my phone but it seems that HREF is a complete and valid url.


we need have a valid url before we `location.href = '/foo'`, it's same in browser. `/foo` only a path, **it's not valid url**. you can set href `/foo` because it's replace pathname only.
you can test in your browser devtools:

```javascript
location.href = 'about:blank' // the blank page in browser.

location.href = '/foo'

// Uncaught DOMException: Failed to set the 'href' property on 'Location': '/foo' is not a valid URL.
//    at <anonymous>:1:15

```

**Comment by hugo-vrijswijk** [comment]
I hate to be that guy, but any update on this? It's currently blocking me from using happy-dom instead of jsdom

**Comment by capricorn86** [comment]
> I hate to be that guy, but any update on this? It's currently blocking me from using happy-dom instead of jsdom

@hugo-vrijswijk the build for this PR is failing and I would also like to look into the solution a bit more. I am currently working on #677, which adds support for FormData and implements "fetch" into Happy DOM. It is a bit time consuming. I will look into this as soon as I can 😅

File: packages/happy-dom/src/location/Location.ts (hunk 1 above)
Comment (capricorn86) [reply packages/happy-dom/src/location/Location.ts:19]: I this is the only solution. We need to use @ts-ignore here as the types are wrong for the URL library.

**Review by capricorn86 — DISMISSED** [review]

File: packages/happy-dom/test/location/Location.test.ts (hunk 2 above)
Comment (capricorn86) [reply packages/happy-dom/test/location/Location.test.ts]: @ilteoood as @Mas0nShi said, the URL needs to be relative to something and by default the URL is set to "about:blank".

Only setting `location.href = '/foo'` will fail with an error as it is not possible to construct a relative URL from "about:blank". Happy DOM could use a different default value for the URL, but what would that be?

After this fix, you will still have to use a setup script for your tests and set a default URL for the URL:s to be relative from.

**Review by capricorn86 — APPROVED** [review]

File: packages/happy-dom/test/location/Location.test.ts (hunk 2 above)
Comment (capricorn86) [reply packages/happy-dom/test/location/Location.test.ts]: I have added unit tests that demonstrates this.
