### PR TITLE
#771@patch: Don't bubble `focus` and `blur` events through DOM.

### LINKED ISSUE #771: `blur` and `focus` events should not bubble through DOM
**Describe the bug**
When triggering `focus/blur` events on the element its ancestor nodes also receive `focus/blur` when they should not.

Per MDN docs `focus` and `blur` events don't bubble in DOM. But related `focusin` and `focusout` do bubble.
https://developer.mozilla.org/en-US/docs/Web/API/Element/focus_event
https://developer.mozilla.org/en-US/docs/Web/API/Element/blur_event

**Expected behavior**
`focus` or `blur` events should not bubble in DOM.

**Device:**
 - Version 8.7.1

Will open a PR soon with updated test cases.

### PR DESCRIPTION
**Pull request by romansp**
Fixes #771.

Only updated existing `HTMLElement` tests that expect `bubbles` value of `blur/focus` events to be `false` from now.

Actual event bubbling is still covered by `Node.test.ts`.

### CODE REVIEW

File: packages/happy-dom/src/nodes/html-element/HTMLElement.ts [hunk 1]
```diff
@@ -383,9 +383,13 @@ export default class HTMLElement extends Element implements IHTMLElement {
 
 		this.ownerDocument['_activeElement'] = null;
 
-		for (const eventType of ['blur', 'focusout']) {
+		const events = <const>[
+			['blur', false],
+			['focusout', true]
+		];
+		for (const [eventType, bubbles] of events) {
```
Comment (capricorn86) [inline packages/happy-dom/src/nodes/html-element/HTMLElement.ts:390]: I think we can replace the for loop logic with just (the same for the other for loop):
```javascript
this.dispatchEvent(new FocusEvent('blur', {
	bubbles: false,
	composed: true
}));
this.dispatchEvent(new FocusEvent('focusout', {
	bubbles: true,
	composed: true
}));
```

Settings `event._target` and `event._currentTarget` doesn't seem to do anything as it will be set by `dispatchEvent()` anyway.

**Review by capricorn86 — CHANGES_REQUESTED** [review]
Thank you for your contribution! :star2: I just have a small comment.

File: packages/happy-dom/src/nodes/html-element/HTMLElement.ts (hunk 1 above)
Comment (romansp) [reply packages/happy-dom/src/nodes/html-element/HTMLElement.ts]: Sounds good. Updated

**Review by capricorn86 — APPROVED** [review]
Nice! 🌟
