### PR TITLE
#628@patch: Handle style setter in HTMLElement.

### LINKED ISSUE #628: `HTMLElement.style` cannot be set directly
**Describe the bug**

`HTMLElement.style` cannot be set, i.e `element.style = 'display: none'` doesn't work in happy-dom though it works in browsers (even if the `style` property is readonly according to the spec).

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style#setting_styles

> While this property is considered read-only, it is possible to set an inline style by assigning a string directly to the style property. In this case the string is forwarded to [CSSStyleDeclaration.cssText](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/cssText). Using style in this manner will completely overwrite all inline styles on the element.

**To Reproduce**

```ts
const { Window } = require('happy-dom');

const window = new Window();
const document = window.document;
const button = document.createElement('button');
button.style = 'display: none';

console.log(button.outerHTML); // "<button></button>"
```

**Expected behavior**

```ts
const button = document.createElement('button');
button.style = 'display: none';
console.log(button.outerHTML); // should display "<button style="display: none"></button>"
```

**Device:**
 - Version 7.6.0
 - Node 16.17.1

### PR DESCRIPTION
**Pull request by jledentu**
This PR adds a setter on `HTMLElement.style` the reproduce the behaviour of DOM implementations, as explained in #628. 

This also fixes another difference between happy-dom and browser implementations: setting `null` or `''` as `style` (or in `cssText`)  shouldn't remove the `style` attribute.

```ts
element.style.cssText = null;
console.log(element.getAttribute('style')); // displays '', not null
```

Since TypeScript forces a value returned by a getter to be assignable to a setter (see https://github.com/microsoft/TypeScript/pull/42425), the `style` setter accepts a `CSSStyleDeclaration` but then resets the `cssText`, as implemented in some browsers.

Closes #628

### CODE REVIEW

File: packages/happy-dom/src/nodes/html-element/HTMLElement.ts [hunk 1]
```diff
@@ -200,6 +200,16 @@ export default class HTMLElement extends Element implements IHTMLElement {
...
 	}
 
+	/**
+	 * Sets style.
+	 *
+	 * @param cssText Style as text.
+	 * @see https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style#setting_styles
+	 */
+	public set style(cssText: string | CSSStyleDeclaration) {
+		this.setAttribute('style', typeof cssText === 'string' ? <string>cssText : '');
```
Comment (capricorn86) [inline packages/happy-dom/src/nodes/html-element/HTMLElement.ts:210]:
```suggestion
		this.style.cssText = cssText;
```

We have to parse the CSS string before setting it (e.g. `element.style = 'invalid: invalid'` won't work).

**Review by capricorn86 — CHANGES_REQUESTED** [review]
Nice contribution! :star2: 

I just found a minor thing.

File: packages/happy-dom/src/nodes/html-element/HTMLElement.ts (hunk 1 above)
Comment (jledentu) [reply packages/happy-dom/src/nodes/html-element/HTMLElement.ts]: Thanks, I updated

**Review by capricorn86 — APPROVED** [review]
